os: linux
language: generic
dist: xenial

install:
  - sudo apt-get update && sudo apt-get install -y debootstrap
  - if [ ! -n "$TRAVIS_TAG" ]; then sed -i "s/HYPERWINE_VERSION=\"0.0.0\"/HYPERWINE_VERSION=\"$TRAVIS_COMMIT\"/g" hyperwine.sh; fi
  - if [ -n "$TRAVIS_TAG" ]; then sed -i "s/HYPERWINE_VERSION=\"0.0.0\"/HYPERWINE_VERSION=\"$TRAVIS_TAG\"/g" hyperwine.sh; fi

script:
  - bash build.sh

         


notifications:
  email: false